name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: |
            n8n-claude-prompt-system:latest
            n8n-claude-prompt-system:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max